openapi: 3.0.3
info:
  title: Clean Architecture Api Specification 
  description: Clean Architecture Api Specification 
  version: 1.0.1
servers:
  - url: 'https://localhost:5000'
    description: Local Development Server

paths:
  /ToDoItems:
    get:
      operationId: ToDoItem.List
      description: "Gets a list of all ToDoItems"
      tags:
        - TodoItemEndpoints
      responses: 
        200:
          description: A list of ToDo Items
          content: 
           application/json:
             schema: 
               type: array
               items: 
                 $ref: '#/components/schemas/ToDoItemResponse'
    put:
      operationId: ToDoItem.Update
      description: Updates a ToDoItem
      tags:
        - TodoItemEndpoints
      responses: 
        200:
          description: The updated ToDo Item
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/ToDoItemResponse'
    post:
      operationId: ToDoItem.Create
      requestBody: 
        content: 
          application/json:
            schema: 
              $ref: '#/components/schemas/NewToDoItemRequest'
      tags:
        - TodoItemEndpoints
      summary: Creates a new ToDoItem
      description:  Creates a new ToDoItem
      responses:
        '200': # status code
          description: A ToDoItemResponse
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ToDoItemResponse'
  /ToDoItems/{id}:
      get:
        operationId: ToDoItem.GetById
        tags:
          - TodoItemEndpoints
        parameters:
          - in: path
            name: id
            required: true
            schema: 
              type: integer
        responses: 
          '200':
            description: Gets a single ToDoItem by Id
            content: 
              application/json:
                schema: 
                  $ref : '#/components/schemas/ToDoItemResponse'
      delete:
        operationId: ToDoItem.Delete
        parameters:
          - in: path
            name: id
            required: true
            schema: 
              type: integer
        tags:
          - TodoItemEndpoints
        summary: Deletes a ToDoItem
        description: Deletes a ToDoItem
        responses:
          '200': # status code
            description: No Content

components:
  schemas:
    UpdateToDoItemRequest:
      type: object
      properties:
        Id:
          type: integer
        Title:
          type: string
        Description:
          type: string
    NewToDoItemRequest:
      type: object
      properties:
        Title:
          type: string
        Description:
          type: string
    ToDoItemResponse:
        type: object
        properties:
          Id:
            type: integer
          Title:
            type: string
          Description:
            type: string
          IsDone:
            type: boolean
          
     
  
  
